languages:
  Python: true

engines:
  pep8:
    enabled: true
    checks:
      # Disable line length (> 79) check
      E501:
        enabled: false
  radon:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
        python:
          # bump up the mass, as the default
          # was creating some unnecessary noise
          # in duplication reports
          mass_threshold: 40

ratings:
  paths:
  - "**.py"

exclude_paths:
  - "*/site-packages/*"
  - "usaspending_api/*/migrations/*"
