language: python

python:
- "3.5"

services: 
- postgresql
- elasticsearch

addons:
  postgresql: "9.6"

env:
  global:
  - DATABASE_URL=postgres://postgres@localhost/usaspending_api
  - DJANGO_SETTINGS_MODULE='usaspending_api.settings'
  - ES_HOSTNAME='http://localhost:9200'

install:
- pip install -r requirements/requirements.txt
- pip install coveralls

before_script:
- psql -c "CREATE DATABASE usaspending_api;" -U postgres
- psql -c "CREATE USER readonly;"
- sed -i 's/ES_HOSTNAME = ""/ES_HOSTNAME = os.environ.get("ES_HOSTNAME")/' usaspending_api/settings.py

script:
- flake8
- pytest --cov=usaspending_api --local=false


after_success:
- codeclimate-test-reporter
#- coveralls
