language: python

python:
  - '3.5'
  - '3.7'

services:
  - postgresql

addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
  global:
  - USASPENDING_DB_USER=postgres
  - DATABASE_URL=postgres://${USASPENDING_DB_USER}@localhost/usaspending_api
  - DJANGO_SETTINGS_MODULE='usaspending_api.settings'
  - ES_HOSTNAME='http://localhost:9200'
  - BROKER_DB_HOST=localhost
  - BROKER_DB_PORT=5435
  - BROKER_DB_USER=admin
  - BROKER_DB_PASSWORD=root
  - BROKER_DB_DBNAME=data_broker
  - DATA_BROKER_DATABASE_URL=postgres://${BROKER_DB_USER}:${BROKER_DB_PASSWORD}@${BROKER_DB_HOST}:${BROKER_DB_PORT}/${BROKER_DB_DBNAME}
  - BROKER_REPO_FOLDER=${TRAVIS_BUILD_DIR}/../data-act-broker-backend

before_install:
  - npm install dredd@5.4.1 --global

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then travis_retry pip install -r requirements/requirements_3-7.txt; else travis_retry pip install -r requirements/requirements.txt; fi
  - pip install coveralls
  # Checkout dependent broker code used to spin up a broker integration test db. Put it in its own folder alongside this repo's code
  - git clone --branch ftr/dev-1526-broker-integ-test-db --single-branch --depth 1 https://github.com/fedspendingtransparency/data-act-broker-backend.git ${BROKER_REPO_FOLDER}

before_script:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.1.1.deb && sudo dpkg -i --force-confnew elasticsearch-6.1.1.deb && sudo service elasticsearch restart
  - sleep 10  # recommended by Travis to ensure Elasticsearch has time to spin up
  - psql -c "CREATE DATABASE usaspending_api;" -U ${USASPENDING_DB_USER}
  - psql -c "CREATE USER readonly;"
  # Establish foreign server for dblink to Broker
  - psql --echo-all --set ON_ERROR_STOP=on --set VERBOSITY=verbose --file usaspending_api/database_scripts/extensions/extensions.sql
  - eval "cat <<< \"$(<usaspending_api/database_scripts/servers/broker_server.sql)\"" > usaspending_api/database_scripts/servers/broker_server.sql
  - psql --echo-all --set ON_ERROR_STOP=on --set VERBOSITY=verbose --file usaspending_api/database_scripts/servers/broker_server.sql
  - python manage.py migrate
  - psql -c "select srvname from pg_foreign_server where srvname = 'broker_server'"
  # Spin up Broker database in a container for ETL integration tests
  - cd ${BROKER_REPO_FOLDER}
  - cp dataactcore/config_example.yml dataactcore/config.yml
  - cp dataactcore/local_config_example.yml dataactcore/local_config.yml
  - cp dataactcore/local_secrets_example.yml dataactcore/local_secrets.yml
  - date
  - docker-compose up -d dataact-broker-db dataact-broker-init-db
  - date
  - sleep 10  # wait for Postgres to be up
  - cd ${TRAVIS_BUILD_DIR}

script:
  - psql --echo-all --set ON_ERROR_STOP=on --set VERBOSITY=verbose -c "SELECT * FROM dblink('broker_server','SELECT now()') AS broker_time(the_now datetime)"
  - flake8
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then black --check . ; fi
  - python manage.py check_for_endpoint_documentation
  - pytest --ignore-glob='**/tests/integration/*' --cov=usaspending_api
  - pytest --override-ini=python_files='**/tests/integration/test_*.py **/tests/integration/*_test.py' --cov=usaspending_api --cov-append --cov-report term
  # - dredd  (Disable dredd until test data is loaded into DB for API responses)

after_success:
  - codeclimate-test-reporter
