language: python

python: 
- "3.3"
- "3.4"
- "3.5"

services: postgresql

env:
  global:
  - DATABASE_URL=postgres://postgres@localhost/usaspending_api

install: "pip install -r requirements.txt"

before_script:
- psql -c "CREATE DATABASE usaspending_api;" -U postgres

script: pytest

