---
# ------------------------------------------------------------------------------
# Example
# ------------------------------------------------------------------------------
debug: true

# define local flag to affect location of downloads
is_local: true

# AWS Region for USAspending Infrastructure
usaspending_aws_region: ""

# AWS locations for CSV files
csv_local_path: "csv_downloads"
download_env: ""
bulk_download_local_path: "bulk_downloads"

bulk_download_s3_bucket_name: ""
bulk_download_s3_redirect_dir: "generated_downloads"
bulk_download_sqs_queue_name: ""
monthly_download_s3_bucket_name: ""
monthly_download_s3_redirect_dir: "award_data_archive"
broker_agency_bucket_name: ""
fpds_bucket_name: ""

deleted_transactions_s3_bucket_name: ""
state_data_bucket: ""
rosetta_dict_s3_path: "da-public-files/user_reference_docs/DATA Transparency Crosswalk.xlsx"